export const ADD_CLICK = 'ADD_CLICK';

export const FETCH_TEAMS_REQUEST = 'FETCH_TEAMS_REQUEST';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
export const FETCH_TEAMS_FAILURE = 'FETCH_TEAMS_FAILURE';

export const START_SESSION = 'START_SESSION';

export const SET_SESSIONCLICKS = 'SET_SESSIONCLICKS';
